In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import joblib

In [4]:
# dataframe = pd.read_csv('allfeatures_3min_50_1.csv').copy()

In [5]:
data = pd.read_csv('allfeatures_3min_120_10.csv').copy()

LOW = blue \
MEDIUM = green \
HIGH = red

In [6]:
# dataframe['arousal_color'] = dataframe['arousal'].apply(lambda x: 'b' if x == 'LOW' else ('g' if x == 'MEDIUM' else 'r'))

In [7]:
# dataframe.dropna(inplace=True)
# dataframe.drop(columns=data.columns[data.eq(0).any()])
# dataframe.shape

In [8]:
# data = dataframe.copy()

Drop all NaN values & Drop all Columns which are only 0 and infinity

In [9]:
# none_rows_arousal = data[data['arousal'] == 'NONE'].sum()
# print(none_rows_arousal)
# none_rows_valence = data[data['valence'] == 'NONE'].sum()
# print(none_rows_valence)

In [10]:
data.dropna(inplace=True)
data = data.drop(columns=data.columns[data.eq(0).any()])
data.shape

(11824, 101)

In [11]:
data.tail()

datetime_mean   datetime_std  datetime_min  datetime_max  datetime_ptp  \
11819   6.319453e+07  139324.598127    62953400.0    63435720.0      482320.0   
11820   6.324483e+07  110301.596968    63054110.0    63435720.0      381610.0   
11821   6.329515e+07   81280.291152    63154640.0    63435720.0      281080.0   
11822   6.334549e+07   52243.071219    63255220.0    63435720.0      180500.0   
11823   6.339587e+07   23126.282525    63356020.0    63435720.0       79700.0   

       datetime_sum  datetime_energy  datetime_kurtosis  datetime_rms  \
11819  7.577024e+10     4.788288e+18          -1.199562  6.319468e+07   
11820  6.001935e+10     3.795925e+18          -1.200170  6.324493e+07   
11821  4.424331e+10     2.800391e+18          -1.200920  6.329520e+07   
11822  2.844213e+10     1.801682e+18          -1.201091  6.334551e+07   
11823  1.261578e+10     7.997884e+17          -1.200461  6.339588e+07   

       datetime_lineintegral  ...    l2_iqr  l2_iqr_5_95    l2_pct_5  \
11819               482320.0  ...  240980.0     434031.0  62977579.0   
11820               381610.0  ...  190920.0     343476.0  63073170.0   
11821               281080.0  ...  140655.0     252991.0  63168690.0   
11822               180500.0  ...   90340.0     162480.0  63264240.0   
11823                79700.0  ...   39865.0      71731.0  63360009.0   

        l2_pct_95  l2_entropy  l2_svd_entropy  reportId  arousal   valence  \
11819  63411610.0    7.089241        0.000002       330     HIGH  POSITIVE   
11820  63416646.0    6.855407        0.000003       330     HIGH  POSITIVE   
11821  63421681.0    6.549650        0.000003       330     HIGH  POSITIVE   
11822  63426720.0    6.107023        0.000003       330     HIGH  POSITIVE   
11823  63431740.0    5.293305        0.000001       330     HIGH  POSITIVE   

          context  
11819  VIEW_BOOTH  
11820  VIEW_BOOTH  
11821  VIEW_BOOTH  
11822  VIEW_BOOTH  
11823  VIEW_BOOTH  

[5 rows x 101 columns]

In [12]:
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_columns', None)
# pd.set_option('display.expand_frame_repr', False)
# np.isinf(data).sum()

Drop Entropy because its only 0

In [13]:
data.drop(["x_entropy", "y_entropy", "z_entropy"], axis=1, inplace=True)
data.shape

(11824, 98)

Pop Emotion Labels for scaling

In [14]:
reportid = data.pop('reportId')
arousal = data.pop('arousal')
valence = data.pop('valence')
context = data.pop('context')
data.shape

(11824, 94)

Scale Data


In [15]:
scaler = StandardScaler()
scaler.fit(data)
scaled_data = scaler.transform(data)
scaled_data = pd.DataFrame(scaled_data)
scaled_data.describe().round(3)

0          1          2          3          4          5   \
count  11824.000  11824.000  11824.000  11824.000  11824.000  11824.000   
mean      -0.000      0.000     -0.000      0.000     -0.000     -0.000   
std        1.000      1.000      1.000      1.000      1.000      1.000   
min       -1.463     -1.747     -1.499     -1.426     -1.747     -1.101   
25%       -0.844     -0.906     -0.844     -0.846     -0.906     -0.815   
50%       -0.099     -0.039     -0.109     -0.095     -0.040     -0.303   
75%        0.808      0.828      0.803      0.805      0.828      0.551   
max        2.364      1.698      2.399      2.327      1.697      3.974   

              6          7          8          9   ...         84         85  \
count  11824.000  11824.000  11824.000  11824.000  ...  11824.000  11824.000   
mean       0.000      0.000     -0.000      0.000  ...      0.000     -0.000   
std        1.000      1.000      1.000      1.000  ...      1.000      1.000   
min       -0.778     -2.970     -1.457     -1.747  ...     -1.457     -1.747   
25%       -0.704     -0.095     -0.845     -0.906  ...     -0.845     -0.906   
50%       -0.419     -0.009     -0.099     -0.041  ...     -0.099     -0.041   
75%        0.314      0.070      0.808      0.826  ...      0.808      0.826   
max        5.223     80.600      2.364      2.156  ...      2.364      2.156   

              86         87         88         89         90         91  \
count  11824.000  11824.000  11824.000  11824.000  11824.000  11824.000   
mean       0.000      0.000     -0.000     -0.000      0.000      0.000   
std        1.000      1.000      1.000      1.000      1.000      1.000   
min       -1.747     -1.746     -1.747     -1.747     -1.495     -1.429   
25%       -0.905     -0.905     -0.906     -0.906     -0.844     -0.848   
50%       -0.038     -0.039     -0.039     -0.039     -0.108     -0.096   
75%        0.829      0.830      0.828      0.828      0.803      0.807   
max        1.711      1.702      1.700      1.697      2.396      2.331   

              92         93  
count  11824.000  11824.000  
mean      -0.000      0.000  
std        1.000      1.000  
min       -5.280     -0.392  
25%       -0.507     -0.356  
50%        0.284     -0.324  
75%        0.744     -0.176  
max        1.072     14.142  

[8 rows x 94 columns]

<font size="10">PCA</font>

In [16]:
# pca = PCA(0.95)
# pca.fit(scaled_data)
# scaled_data = pca.transform(scaled_data)
# scaled_data = pd.DataFrame(scaled_data)

<font size=5>Adding back arousal and valence to the PCA dataframe<font>

In [17]:
scaled_data['arousal'] = arousal
scaled_data['valence'] = valence
scaled_data["reportId"] = reportid
scaled_data.shape
scaled_data.head()

0         1         2         3         4         5         6  \
0 -1.420706  1.695492 -1.457058 -1.383598  1.696153 -0.840301 -0.760652   
1 -1.418556  1.598988 -1.452760 -1.383598  1.599617 -0.844925 -0.760830   
2 -1.416407  1.502497 -1.448460 -1.383598  1.503053 -0.849713 -0.761021   
3 -1.414258  1.406021 -1.444164 -1.383598  1.406584 -0.854664 -0.761225   
4 -1.412108  1.309530 -1.439876 -1.383598  1.310278 -0.859779 -0.761443   

          7         8         9  ...        87        88        89        90  \
0  0.195701 -1.416687  1.693928  ...  1.696264  1.695142  1.695771 -1.453451   
1  0.204235 -1.414857  1.597453  ...  1.600568  1.598580  1.599259 -1.449369   
2  0.215159 -1.413013  1.500949  ...  1.504099  1.501894  1.502959 -1.445294   
3  0.229578 -1.411156  1.404541  ...  1.407631  1.405581  1.406428 -1.441211   
4  0.236965 -1.409286  1.308296  ...  1.311934  1.309010  1.309959 -1.437129   

         91        92        93  arousal  valence  reportId  
0 -1.387349  1.041059  4.058500      LOW  NEUTRAL         1  
1 -1.387135  1.011394  3.873081      LOW  NEUTRAL         1  
2 -1.386919  0.980660  3.691967      LOW  NEUTRAL         1  
3 -1.386705  0.948810  3.516263      LOW  NEUTRAL         1  
4 -1.386489  0.915790  3.346762      LOW  NEUTRAL         1  

[5 rows x 97 columns]

<font size="5">Check for every combination of Valence and Arousal</font>

In [18]:
# Group the data by arousal and valence columns
grouped = scaled_data.groupby(["arousal", 'valence'])

# Count the number of unique combinations of arousal and valence within each group
unique_combinations = grouped.size().reset_index(name='count')
print("unique_combinations:", unique_combinations)

# Check if all different combinations of arousal and valence are present
all_combinations_present = len(unique_combinations) == len(arousal.unique()) * len(valence.unique())

print("Are all combinations available? ", all_combinations_present)

# Calculate the percentage distribution of unique combinations
percentage_distribution = unique_combinations['count'] / len(data) * 100
percentage_distribution = percentage_distribution.round(2)

# Display the percentage distribution
print(percentage_distribution)

unique_combinations:   arousal   valence  count
0    HIGH  NEGATIVE    144
1    HIGH   NEUTRAL    490
2    HIGH  POSITIVE   2190
3     LOW  NEGATIVE    576
4     LOW   NEUTRAL   1332
5     LOW  POSITIVE    464
6  MEDIUM  NEGATIVE    288
7  MEDIUM   NEUTRAL   3722
8  MEDIUM  POSITIVE   2618
Are all combinations available?  True
0     1.22
1     4.14
2    18.52
3     4.87
4    11.27
5     3.92
6     2.44
7    31.48
8    22.14
Name: count, dtype: float64


<font size=5>Encoding the Arousal and Valence values</font>

In [19]:
scaled_data['arousal_valence'] = scaled_data['arousal'] + '_' + scaled_data['valence']

In [20]:
print(scaled_data.isna().sum())

0                  0
1                  0
2                  0
3                  0
4                  0
                  ..
93                 0
arousal            0
valence            0
reportId           0
arousal_valence    0
Length: 98, dtype: int64


In [21]:
scaled_data.dropna(subset=['arousal', 'valence', 'reportId', 'arousal_valence'], inplace=True)

In [22]:
print(scaled_data.isna().sum())

0                  0
1                  0
2                  0
3                  0
4                  0
                  ..
93                 0
arousal            0
valence            0
reportId           0
arousal_valence    0
Length: 98, dtype: int64


In [23]:
num_reportid_values = reportid.nunique()
print("Number of different reportid values:", num_reportid_values)

Number of different reportid values: 330


In [24]:
arousal = scaled_data.pop('arousal')
valence = scaled_data.pop('valence')
arousal_valence = scaled_data.pop('arousal_valence')
groups = scaled_data.pop('reportId')

In [25]:
print("arousal_valence: ", arousal_valence.shape)
print("scaled_data: ", scaled_data.shape)
print("groups: ", groups.shape)

arousal_valence:  (11824,)
scaled_data:  (11824, 94)
groups:  (11824,)


In [26]:
scaled_data.head()


0         1         2         3         4         5         6   \
0 -1.420706  1.695492 -1.457058 -1.383598  1.696153 -0.840301 -0.760652   
1 -1.418556  1.598988 -1.452760 -1.383598  1.599617 -0.844925 -0.760830   
2 -1.416407  1.502497 -1.448460 -1.383598  1.503053 -0.849713 -0.761021   
3 -1.414258  1.406021 -1.444164 -1.383598  1.406584 -0.854664 -0.761225   
4 -1.412108  1.309530 -1.439876 -1.383598  1.310278 -0.859779 -0.761443   

         7         8         9   ...        84        85        86        87  \
0  0.195701 -1.416687  1.693928  ... -1.416687  1.693928  1.698627  1.696264   
1  0.204235 -1.414857  1.597453  ... -1.414857  1.597453  1.601359  1.600568   
2  0.215159 -1.413013  1.500949  ... -1.413013  1.500949  1.504863  1.504099   
3  0.229578 -1.411156  1.404541  ... -1.411156  1.404541  1.408367  1.407631   
4  0.236965 -1.409286  1.308296  ... -1.409286  1.308296  1.311099  1.311934   

         88        89        90        91        92        93  
0  1.695142  1.695771 -1.453451 -1.387349  1.041059  4.058500  
1  1.598580  1.599259 -1.449369 -1.387135  1.011394  3.873081  
2  1.501894  1.502959 -1.445294 -1.386919  0.980660  3.691967  
3  1.405581  1.406428 -1.441211 -1.386705  0.948810  3.516263  
4  1.309010  1.309959 -1.437129 -1.386489  0.915790  3.346762  

[5 rows x 94 columns]

In [27]:
scaled_data.tail()

0         1         2         3         4         5         6   \
11819  1.086354 -1.295944  1.114124  1.058008 -1.295728 -0.614825 -0.356237   
11820  1.088506 -1.392453  1.118429  1.058008 -1.392389 -0.717330 -0.443676   
11821  1.090659 -1.488956  1.122725  1.058008 -1.488877 -0.819999 -0.531394   
11822  1.092812 -1.585513  1.127024  1.058008 -1.585413 -0.922832 -0.619393   
11823  1.094968 -1.682334  1.131332  1.058008 -1.682160 -1.025829 -0.707671   

             7         8         9   ...        84        85        86  \
11819  0.085436  1.086321 -1.296075  ...  1.086321 -1.296075 -1.296613   
11820 -0.057880  1.088471 -1.392675  ...  1.088471 -1.392675 -1.393109   
11821 -0.234671  1.090623 -1.489102  ...  1.090623 -1.489102 -1.489605   
11822 -0.275101  1.092776 -1.585577  ...  1.092776 -1.585577 -1.585329   
11823 -0.126470  1.094931 -1.682264  ...  1.094931 -1.682264 -1.682598   

             87        88        89        90        91        92        93  
11819 -1.295797 -1.296339 -1.295811  1.111376  1.060866 -1.196099 -0.368367  
11820 -1.392266 -1.392464 -1.392382  1.115462  1.061081 -1.459659 -0.367858  
11821 -1.488734 -1.488983 -1.488878  1.119545  1.061297 -1.804287 -0.366093  
11822 -1.585974 -1.585597 -1.585403  1.123629  1.061513 -2.303185 -0.361787  
11823 -1.681671 -1.682519 -1.682180  1.127723  1.061727 -3.220350 -0.379242  

[5 rows x 94 columns]

In [28]:
print(scaled_data.isna().sum())
print()

0     0
1     0
2     0
3     0
4     0
     ..
89    0
90    0
91    0
92    0
93    0
Length: 94, dtype: int64



LABEL ENCODING

In [29]:
from sklearn.preprocessing import LabelEncoder

# Convert the target variable from string to integer using label encoding
label_encoder = LabelEncoder()
arousal_valence_encoded = label_encoder.fit_transform(arousal_valence)
arousal_valence_encoded = pd.DataFrame(arousal_valence_encoded, columns=['Encoded'])

print("Arousal Valence Encoded:", arousal_valence_encoded)

# Get the unique classes and their corresponding encoded values
classes = label_encoder.classes_
encoded_values = label_encoder.transform(classes)

# Create a dictionary to map encoded values to original strings
encoding_map = dict(zip(encoded_values, classes))

print("Encoding map:", encoding_map)

Arousal Valence Encoded:        Encoded
0            4
1            4
2            4
3            4
4            4
...        ...
11819        2
11820        2
11821        2
11822        2
11823        2

[11824 rows x 1 columns]
Encoding map: {0: 'HIGH_NEGATIVE', 1: 'HIGH_NEUTRAL', 2: 'HIGH_POSITIVE', 3: 'LOW_NEGATIVE', 4: 'LOW_NEUTRAL', 5: 'LOW_POSITIVE', 6: 'MEDIUM_NEGATIVE', 7: 'MEDIUM_NEUTRAL', 8: 'MEDIUM_POSITIVE'}


In [30]:
import time
from sklearn.model_selection import StratifiedGroupKFold, cross_val_predict
from xgboost import XGBClassifier
from skopt import BayesSearchCV
from sklearn.metrics import classification_report, accuracy_score, f1_score, precision_score, recall_score

# Define the number of folds
n_splits = 5

# Create the StratifiedGroupKFold object
sgkf = StratifiedGroupKFold(n_splits=n_splits)

# Create XGBClassifier instance
xgb = XGBClassifier(objective='multi:softmax', num_class=9, random_state=42)

fold = 1

# Define the parameter search space
param_space = {
    'learning_rate': (0.01, 0.3, 'log-uniform'),
    'n_estimators': (100, 1000),
    'max_depth': (3, 10),
    'min_child_weight': (1, 10),
    'subsample': (0.5, 1.0),
    'colsample_bytree': (0.5, 1.0),
    'gamma': (0, 10),
    'reg_alpha': (0, 10),  # alpha in xgboost is reg_alpha
    'reg_lambda': (0, 10), # lambda in xgboost is reg_lambda
}

# Initialize BayesSearchCV
opt = BayesSearchCV(
                estimator=xgb,
                search_spaces=param_space, 
                cv=sgkf, 
                random_state=42, 
                verbose=2, 
                n_jobs=-1,
                n_iter=30, 
                n_points=1,
                pre_dispatch='2*n_jobs',
                scoring='accuracy'
                )  
print("BayesSearchCV initialized")

# Start the timer
start_time = time.time()
print("timer started")

# Perform hyperparameter optimization
opt.fit(scaled_data, arousal_valence_encoded, groups=groups)

# Stop the timer
end_time = time.time()

print("end timer")
print(f"optimizer fit")

# Calculate the total time taken
total_time = end_time - start_time

# Access the cross-validation results
cv_results = opt.cv_results_

# Get the best estimator
best_est = opt.best_estimator_

print(f"Best parameters found: {opt.best_params_}")

BayesSearchCV initialized
timer started
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds 

In [31]:
from sklearn.metrics import classification_report, accuracy_score, f1_score, precision_score, recall_score
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix

# Get cross-validated predictions on the train set for evaluation
y_pred = cross_val_predict(best_est, scaled_data, arousal_valence_encoded, groups=groups, cv=sgkf)

accuracy = accuracy_score(arousal_valence_encoded, y_pred)
f1 = f1_score(arousal_valence_encoded, y_pred, average='macro')
precision = precision_score(arousal_valence_encoded, y_pred, average='macro')
recall = recall_score(arousal_valence_encoded, y_pred, average='macro')


# Compute the confusion matrix
cm = confusion_matrix(arousal_valence_encoded, y_pred)

# Print the confusion matrix
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[   0    0   14    0    0    0    0   80   50]
 [   0    0   75    0    1    1    0  324   89]
 [   0   30  264    0   39    0    0 1285  572]
 [   0    0   22    0   11    0    0  464   79]
 [   0    3  170    0   69    0    0  820  270]
 [   0    4    6    0   12    0    0  260  182]
 [   0    0   99    0    0    0    0  159   30]
 [   0   21  432   16  169    6    0 2284  794]
 [   0    6  434    0   55    0    0 1417  706]]


c:\Users\duong\anaconda3\envs\batf\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [32]:
print("accuracy: ", accuracy)
print("f1-score: ", f1)
print("precision: ", precision)
print("recall: ", recall)

accuracy:  0.2810385656292287
f1-score:  0.10095201734051912
precision:  0.10496223030662809
recall:  0.117296647556366


In [33]:
import mlflow
from mlflow.models import infer_signature

mlflow.set_tracking_uri(uri="http://localhost:5000")

In [34]:
import mlflow.data
from mlflow.data.pandas_dataset import PandasDataset

In [35]:
# Create new experiment
mlflow.set_experiment("Hyperparameter Tuning") #PCA_95_RF_SGKF

# Start a new MLflow run
with mlflow.start_run():

    # Create an instance of a PandasDataset
    dataset = mlflow.data.from_pandas(
    scaled_data, name="allfeatures_3min_120_10.csv"
    )

    # Log the hyperparameters
    mlflow.log_params(opt.best_params_)

    # Log the model tag
    mlflow.set_tag("NoPCA", "XGBOOST", "SGKF")

    # Log the cross-validation results
    for i in range(len(cv_results['params'])):
        mlflow.log_metric("mean_test_score", cv_results['mean_test_score'][i], step=i)
        mlflow.log_metric("std_test_score", cv_results['std_test_score'][i], step=i)

    # Log the feature importances
    feature_importances = best_est.feature_importances_
    for i, importance in enumerate(feature_importances):
        mlflow.log_metric(f"feature_{i}_importance", importance)

    # Log the number of features
    mlflow.log_param("num_features", len(feature_importances))

    # Log the number of samples
    mlflow.log_param("num_samples", len(scaled_data))

    # Log the number of classes
    mlflow.log_param("num_classes", len(arousal_valence_encoded['Encoded'].unique()))

    # Log the number of splits
    mlflow.log_param("num_splits", n_splits)

    # Log the number of iterations
    mlflow.log_param("num_iterations", 25)

    # Log the search space
    mlflow.log_param("search_space", param_space)

    # Log the best score
    mlflow.log_metric("best_score", opt.best_score_)

    # Log the best parameters
    mlflow.log_param("best_params", opt.best_params_)

    # Log the best index
    mlflow.log_param("best_index", opt.best_index_)

    #log the total time taken
    mlflow.log_param("total_time", total_time)

    #log the accuracy
    mlflow.log_metric("accuracy", accuracy)

    #log the f1-score
    mlflow.log_metric("f1-score", f1)
    
    #log the precision
    mlflow.log_metric("precision", precision)

    #log the recall
    mlflow.log_metric("recall", recall)

    # # Log the confusion matrix
    # mlflow.log_metric("confusion_matrix", cm)

    # Log metadata (number of rows and columns)
    mlflow.log_param("num_rows", scaled_data.shape[0])
    mlflow.log_param("num_columns", scaled_data.shape[1])

    # Save the Pandas dataset locally
    dataset_path = "allfeatures_3min_50_1.csv"
    scaled_data.to_csv(dataset_path, index=False)

    # Log the dataset as an artifact in the current run
    mlflow.log_artifact(dataset_path, artifact_path="datasets")

    # Log the best estimator
    mlflow.sklearn.log_model(opt.best_estimator_, "best_model", signature=infer_signature(scaled_data, opt.best_estimator_.predict(scaled_data)))




2024/08/23 00:45:31 INFO mlflow.tracking._tracking_service.client: 🏃 View run enchanting-shad-152 at: http://localhost:5000/#/experiments/386650147372629254/runs/66564445f64d4738badbe1d876ef0a90.
2024/08/23 00:45:31 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://localhost:5000/#/experiments/386650147372629254.
